import {BrandMark} from './src/ui/BrandMark';
import {webRoute,webTabPaths,webSheetPath} from './src/data/webNavigation';
import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, BackHandler, KeyboardAvoidingView, Modal, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, useWindowDimensions, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { AppProvider, useApp } from './src/data/AppProvider';
import { NavigationContext, type Sheet, type Tab } from './src/ui/navigation';
import { C, Button, Icon, IconButton, Txt, type IconName } from './src/ui/theme';
import { buzz, errorText } from './src/ui/helpers';
import { Home } from './src/screens/Home';
import { Explore } from './src/screens/Explore';
import { Activity } from './src/screens/Activity';
import { Impact } from './src/screens/Impact';
import { Profile } from './src/screens/Profile';
import { Detail } from './src/screens/Detail';
import { Welcome } from './src/screens/Welcome';
import { FormContent } from './src/screens/Forms';

const tabs: {id:Tab;label:string;icon:IconName;active:IconName}[]=[{id:'home',label:'Home',icon:'home-outline',active:'home'},{id:'explore',label:'Explore',icon:'compass-outline',active:'compass'},{id:'activity',label:'Activity',icon:'calendar-outline',active:'calendar'},{id:'impact',label:'Impact',icon:'flower-outline',active:'flower'},{id:'profile',label:'You',icon:'person-outline',active:'person'}];
export default function App(){return <SafeAreaProvider><AppProvider><Root/></AppProvider></SafeAreaProvider>;}
function Root(){const app=useApp(),{height,width}=useWindowDimensions();const desktop=Platform.OS==='web'&&width>=960;const[exploreCause,setExploreCause]=useState('All');const[tab,setTab]=useState<Tab>('home'),[detail,setDetail]=useState<string|null>(null),[sheet,setSheet]=useState<Sheet|null>(null),[toast,setToast]=useState('');const scroll=useRef<ScrollView>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const openSheet=(value:Sheet)=>{const path=webSheetPath(value);if(Platform.OS==='web'&&path)window.history.pushState({},'',path);setSheet(value);};
 const closeSheet=()=>{if(Platform.OS==='web'&&sheet&&webSheetPath(sheet))window.history.replaceState({},'',detail?`/opportunity?id=${encodeURIComponent(detail)}`:webTabPaths[tab]);setSheet(null);};
 const notify=(value:string)=>{setToast(value);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),6000);};
 const navigate=(next:Tab,cause?:string)=>{if(Platform.OS==='web')window.history.pushState({},'',webTabPaths[next]);if(next==='explore')setExploreCause(cause??'All');buzz();setTab(next);setDetail(null);scroll.current?.scrollTo({y:0,animated:false});};const showDetail=(id:string)=>{if(Platform.OS==='web')window.history.pushState({},'',`/opportunity?id=${encodeURIComponent(id)}`);setDetail(id);scroll.current?.scrollTo({y:0,animated:false});};
 useEffect(()=>{if(Platform.OS!=='web'||!app.ready)return;window.history.scrollRestoration='manual';const applyRoute=()=>{const route=webRoute(window.location.pathname,window.location.search);setTab(route.tab);setDetail(route.detail??null);setSheet(route.sheet??null);requestAnimationFrame(()=>scroll.current?.scrollTo({y:0,animated:false}));};applyRoute();window.addEventListener('popstate',applyRoute);return()=>window.removeEventListener('popstate',applyRoute);},[app.ready]);
 useEffect(()=>{if(app.passwordRecovery)setSheet({kind:'password'});},[app.passwordRecovery]);
 useEffect(()=>{if(app.error)notify(app.error);},[app.error]);
 useEffect(()=>{const handler=BackHandler.addEventListener('hardwareBackPress',()=>{if(sheet){setSheet(null);return true;}if(detail){setDetail(null);return true;}if(tab!=='home'){setTab('home');return true;}return false;});return()=>handler.remove();},[detail,sheet,tab]);
 useEffect(()=>{if(app.mode==='signedOut'){setTab('home');setDetail(null);}},[app.mode]);
 if(!app.ready)return <View style={{flex:1,backgroundColor:C.bg,alignItems:'center',justifyContent:'center'}}><ActivityIndicator size="large" color={C.orange}/><Txt style={{marginTop:20}}>A little good is on its way.</Txt></View>;
 return <NavigationContext.Provider value={{tab,navigate,detail:showDetail,sheet:openSheet,close:closeSheet,notify}}><StatusBar style="dark"/><View style={{flex:1,backgroundColor:desktop?C.bg:'#EAE7DE',alignItems:'center',flexDirection:desktop?'row':'column',justifyContent:'center'}}>{desktop&&app.mode!=='signedOut'&&<View style={{width:228,alignSelf:'stretch',padding:20,paddingTop:30,borderRightWidth:1,borderColor:C.line,gap:28,backgroundColor:C.white}}><View style={[{flexDirection:'row',alignItems:'center',gap:9}]}><BrandMark size={34}/><Txt style={{fontSize:22,fontWeight:'900',letterSpacing:-1}}>voluforge</Txt></View><View accessibilityRole="tablist" style={{gap:5}}>{tabs.map(t=><Pressable key={t.id} accessibilityRole="tab" accessibilityLabel={t.label} accessibilityState={{selected:tab===t.id&&!detail}} onPress={()=>navigate(t.id)} style={{paddingVertical:14,paddingHorizontal:16,borderRadius:12,backgroundColor:tab===t.id&&!detail?C.ink:'transparent',flexDirection:'row',alignItems:'center',gap:13}}><Icon name={tab===t.id?t.active:t.icon} size={21} color={tab===t.id&&!detail?C.bg:C.ink}/><Txt style={{fontWeight:'700',color:tab===t.id&&!detail?C.bg:C.ink}}>{t.label}</Txt></Pressable>)}</View><View style={{gap:5,marginTop:8,borderTopWidth:1,borderColor:C.line,paddingTop:20}}>{[{title:'Community needs',icon:'earth-outline' as IconName,kind:'insights' as const},{title:'Partner workspace',icon:'people-outline' as IconName,kind:'partner' as const}].map(item=><Pressable key={item.kind} accessibilityRole="button" accessibilityLabel={item.title} onPress={()=>openSheet({kind:item.kind})} style={{minHeight:48,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:10,borderRadius:10}}><Icon name={item.icon} size={19} color={C.muted}/><Txt style={{fontSize:13,fontWeight:'600'}}>{item.title}</Txt></Pressable>)}</View><View style={{marginTop:'auto',gap:10}}><Txt style={{fontSize:12,color:C.muted,lineHeight:20}}>A little time. A lot of good.</Txt><Pressable accessibilityRole="button" onPress={()=>openSheet({kind:'privacy'})}><Txt style={{fontSize:11,color:C.muted}}>Privacy & your data</Txt></Pressable></View></View>}<SafeAreaView style={{flex:1,alignSelf:desktop?'stretch':undefined,minHeight:0,width:'100%',maxWidth:desktop?1180:480,backgroundColor:C.bg,borderLeftWidth:!desktop&&width>480?1:0,borderRightWidth:!desktop&&width>480?1:0,borderColor:C.line}} edges={['top','bottom']}>
 {app.mode==='demo'&&<View style={{paddingVertical:10,paddingHorizontal:20,alignItems:'center',backgroundColor:'#EEEBDC',borderBottomWidth:1,borderColor:C.line}}><Txt style={{fontSize:11,letterSpacing:.25,color:C.muted}}>PREVIEW MODE · FICTIONAL SAMPLE DATA</Txt></View>}
 <ScrollView ref={scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} style={{flex:1}} contentContainerStyle={{flexGrow:1,paddingBottom:app.mode==='signedOut'?15:14}} refreshControl={app.mode!=='signedOut'?<RefreshControl refreshing={app.loading&&!sheet} onRefresh={()=>{void app.refresh().catch(e=>notify(errorText(e)));}} tintColor={C.orange}/>:undefined}>
 {app.mode==='signedOut'?<Welcome/>:!app.profile?<View style={{padding:30,gap:20}}><Txt style={{fontSize:27,fontWeight:'800'}}>Let’s reconnect.</Txt><Txt style={{lineHeight:24}}>{app.error||'Your account data could not be loaded. Please try again.'}</Txt><Button title="Try again" onPress={()=>{void app.refresh().catch(e=>notify(errorText(e)));}}/><Button title="Sign out" variant="outline" onPress={()=>{void app.signOut().catch(e=>notify(errorText(e)));}}/><Button title="Delete account" variant="soft" onPress={()=>setSheet({kind:'delete'})}/></View>:detail?<Detail id={detail} onBack={()=>{if(Platform.OS==='web')window.history.replaceState({},'',webTabPaths[tab]);setDetail(null);scroll.current?.scrollTo({y:0,animated:false});}}/>:tab==='home'?<Home/>:tab==='explore'?<Explore key={exploreCause} initialCause={exploreCause}/>:tab==='activity'?<Activity/>:tab==='impact'?<Impact/>:<Profile/>}
 </ScrollView>
 {app.mode!=='signedOut'&&!desktop&&<View style={{paddingHorizontal:13,paddingTop:8,paddingBottom:Platform.OS==='web'?14:5,backgroundColor:C.bg,borderTopWidth:1,borderColor:C.line}}><View accessibilityRole="tablist" style={{flexDirection:'row',backgroundColor:C.ink,borderRadius:100,padding:6}}>{tabs.map(t=><Pressable key={t.id} accessibilityRole="tab" accessibilityLabel={t.label} accessibilityState={{selected:tab===t.id&&!detail}} onPress={()=>navigate(t.id)} style={{flex:1,minHeight:52,borderRadius:100,backgroundColor:tab===t.id&&!detail?C.bg:'transparent',alignItems:'center',justifyContent:'center',gap:4}}><Icon name={tab===t.id?t.active:t.icon} size={20} color={tab===t.id&&!detail?C.ink:'#C4C5BB'}/><Txt style={{fontSize:9,fontWeight:'600',color:tab===t.id&&!detail?C.ink:'#C4C5BB'}}>{t.label}</Txt></Pressable>)}</View></View>}
 </SafeAreaView></View>
 <Modal visible={!!sheet} transparent animationType={desktop?'fade':'slide'} onRequestClose={closeSheet} statusBarTranslucent><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,justifyContent:desktop?'center':'flex-end',alignItems:'center'}}><Pressable accessibilityRole="button" accessibilityLabel="Close dialog" onPress={closeSheet} style={[StyleSheet.absoluteFill,{backgroundColor:'rgba(18,20,16,.45)'}]}/><SafeAreaView accessibilityViewIsModal style={{backgroundColor:C.bg,width:'100%',maxWidth:desktop?620:480,maxHeight:height*(desktop?.86:.94),borderRadius:desktop?16:undefined,borderTopLeftRadius:desktop?16:28,borderTopRightRadius:desktop?16:28}} edges={['bottom']}>{!desktop&&<View style={{alignItems:'center',paddingTop:10}}><View style={{width:34,height:4,backgroundColor:C.line,borderRadius:5}}/></View>}<View style={{alignItems:'flex-end',paddingHorizontal:18,paddingTop:desktop?16:5}}><IconButton name="close" label="Close dialog" onPress={closeSheet} style={{backgroundColor:C.soft,width:44,height:44}}/></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingHorizontal:25,paddingTop:8,paddingBottom:34}}>{sheet&&<FormContent key={sheet.kind+(sheet.id||'')} sheet={sheet}/>}</ScrollView></SafeAreaView></KeyboardAvoidingView></Modal>
 {!!toast&&<Pressable accessibilityRole="alert" accessibilityLiveRegion="polite" onPress={()=>setToast('')} style={{position:'absolute',bottom:105,alignSelf:'center',width:'88%',maxWidth:430,backgroundColor:C.ink,padding:17,borderRadius:18,boxShadow:'0px 6px 25px rgba(0,0,0,.15)'}}><Txt style={{color:C.white,fontSize:13,lineHeight:20}}>{toast}</Txt></Pressable>}
 </NavigationContext.Provider>;
}
