import React, { useEffect, useState } from 'react';
import { Pressable, View } from 'react-native';
import { useApp } from '../data/AppProvider';
import { useNav } from '../ui/navigation';
import { C, Badge, Button, Chip, Empty, Eyebrow, Icon, Title, Txt, s } from '../ui/theme';
import { day, errorText, hours } from '../ui/helpers';

export function Activity(){const app=useApp(),nav=useNav();const[filter,setFilter]=useState('Accepted'),[now,setNow]=useState(Date.now()),[busy,setBusy]=useState(false);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const accepted=app.applications.filter(a=>a.status==='accepted');const applications=filter==='Accepted'?accepted:app.applications;
 const elapsed=app.timer?Math.max(0,Math.floor((now-Date.parse(app.timer.startedAt))/1000)):0;
 return <View style={{padding:24,paddingTop:29,paddingBottom:36}}><Eyebrow>Keep showing up</Eyebrow><View style={[s.between,{marginTop:12}]}><Title>Your good,{'\n'}in motion.</Title><Pressable accessibilityRole="button" accessibilityLabel="Log service" onPress={()=>nav.sheet({kind:'log'})} style={{backgroundColor:C.ink,width:46,height:46,borderRadius:100,alignItems:'center',justifyContent:'center'}}><Icon name="add" color={C.white}/></Pressable></View>
 {app.timer&&<View style={{backgroundColor:C.peach,padding:22,borderRadius:22,marginTop:24,gap:14}}><View style={s.between}><Eyebrow style={{color:C.ink}}>Service in progress</Eyebrow><View style={{width:8,height:8,borderRadius:10,backgroundColor:C.orange}}/></View><Txt style={{fontSize:46,fontWeight:'800',fontVariant:['tabular-nums'],letterSpacing:-1}}>{String(Math.floor(elapsed/3600)).padStart(2,'0')}:{String(Math.floor(elapsed/60)%60).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</Txt><Txt style={{fontSize:13}}>{app.opportunities.find(o=>o.id===app.applications.find(a=>a.id===app.timer?.applicationId)?.opportunityId)?.title??'Your volunteer session'}</Txt><Button title="Finish & add a note" icon="stop-circle-outline" onPress={()=>nav.sheet({kind:'log',id:app.timer!.applicationId})}/><Pressable accessibilityRole="button" onPress={async()=>{try{await app.cancelTimer();nav.notify('Timer canceled. No hours were submitted.');}catch(e){nav.notify(errorText(e));}}}><Txt style={{textAlign:'center',textDecorationLine:'underline',fontSize:12}}>Discard this timer</Txt></Pressable></View>}
 <View style={[s.row,{gap:8,marginTop:25,marginBottom:23}]}>{['Accepted','Applications','History'].map(f=><Chip key={f} label={f} selected={filter===f} onPress={()=>setFilter(f)}/>)}</View>
 {filter==='History'?<>{app.entries.map(e=>{const o=app.opportunities.find(o=>o.id===e.opportunityId);return <View key={e.id} style={{borderBottomWidth:1,borderColor:C.line,paddingVertical:18,gap:10}}><View style={s.between}><Txt style={{fontWeight:'800',fontSize:17}}>{hours(e.minutes)} hours</Txt><Badge status={e.status}/></View><Txt style={{fontWeight:'600',fontSize:14}}>{o?.title??'Service entry'}</Txt><Txt style={[s.body,{fontSize:12}]}>{day(e.date)} · {e.notes}</Txt>{e.status==='changes_requested'&&<Button title="Revise & resubmit" variant="outline" onPress={()=>nav.sheet({kind:'log',id:e.id})}/>}{e.reviewerNote&&<Txt style={{fontSize:12,color:C.forest}}>Partner note: {e.reviewerNote}</Txt>}</View>})}{!app.entries.length&&<Empty title="Your story starts here" text="Completed service and review updates will appear here."/>}</>:<>{applications.map(a=>{const o=app.opportunities.find(o=>o.id===a.opportunityId);if(!o)return null;return <View key={a.id} style={{borderBottomWidth:1,borderColor:C.line,paddingVertical:19,gap:12}}><View style={s.between}><Eyebrow>{day(o.startsAt)} · {o.remote?'REMOTE':'IN PERSON'}</Eyebrow><Badge status={a.status}/></View><Pressable accessibilityRole="button" onPress={()=>nav.detail(o.id)}><Txt style={{fontSize:23,fontWeight:'800',letterSpacing:-.7}}>{o.title}</Txt><Txt style={{color:C.muted,fontSize:12,marginTop:7}}>{o.organization}</Txt></Pressable>{a.status==='accepted'&&<View style={[s.row,{gap:9,marginTop:5}]}><Button title="Log hours" variant="outline" style={{flex:1,minHeight:45,paddingVertical:10,paddingHorizontal:10}} onPress={()=>nav.sheet({kind:'log',id:a.id})}/><Button title="Start timer" icon="play-outline" disabled={!!app.timer} busy={busy} style={{flex:1,minHeight:45,paddingVertical:10,paddingHorizontal:10}} onPress={async()=>{setBusy(true);try{await app.startTimer(a.id);nav.notify('Timer started. Your session is saved.');}catch(e){nav.notify(errorText(e));}finally{setBusy(false);}}}/></View>}</View>})}{!applications.length&&<Empty icon="calendar-outline" title={filter==='Accepted'?'Make room for something good.':'Your next chapter awaits.'} text="Apply to an opportunity. Once the partner accepts you, you can start logging your service." action={<Button title="Find an opportunity" onPress={()=>nav.navigate('explore')}/>}/>}</>}
 </View>;
}
