import {matchOpportunity} from '../data/impactEngine';
import {impactOpportunity,preferencesFor} from '../data/impact';
import React, { useState } from 'react';
import { Linking, Share, View } from 'react-native';
import { useApp } from '../data/AppProvider';
import { applicationBlocker, remainingPlaces } from '../data/opportunities';
import { useNav } from '../ui/navigation';
import { C, Badge, Button, Chip, Empty, Eyebrow, Icon, IconButton, Rule, Title, Txt, s } from '../ui/theme';
import { OpportunityImage } from '../ui/OpportunityCard';
import { errorText, fullDay, time } from '../ui/helpers';

export function Detail({id,onBack}:{id:string;onBack:()=>void}) {
 const app=useApp(),nav=useNav(),o=app.opportunities.find(o=>o.id===id);const[busy,setBusy]=useState(false);
 if(!o)return <Empty title="Opportunity unavailable" text="This opportunity may have closed or is no longer accessible." action={<Button title="Go back" onPress={onBack}/>}/>;
 const saved=app.savedIds.includes(id),application=app.applications.find(a=>a.opportunityId===id);
 const match=matchOpportunity(impactOpportunity(o),preferencesFor(app.profile));const blocked=applicationBlocker(o,application)||match.blockers[0];
 const save=async()=>{try{await app.saveOpportunity(id);}catch(e){nav.notify(errorText(e));}};
 const share=async()=>{try{await Share.share({message:`${app.mode==='demo'?'DEMO OPPORTUNITY — ':''}${o.title}\n${o.organization}\n${fullDay(o.startsAt)} · ${time(o.startsAt)}\n${o.location}\n\n${o.description}\n\nDiscover ways to give back with VoluForge.`});}catch(e){nav.notify(errorText(e));}};
 return <View style={{padding:24,paddingTop:16,paddingBottom:35}}><View style={s.between}><IconButton name="arrow-back" label="Back" onPress={onBack} style={{backgroundColor:'transparent'}}/><View style={[s.row,{gap:10}]}><IconButton name={saved?'bookmark':'bookmark-outline'} label={saved?'Unsave opportunity':'Save opportunity'} active={saved} onPress={save}/><IconButton name="share-outline" label="Share opportunity" onPress={share}/></View></View>
 <View style={{width:'82%',borderRadius:26,overflow:'hidden',marginTop:25,marginBottom:27}}><OpportunityImage opportunity={o} height={193}/></View><Eyebrow style={{color:C.orange}}>{o.cause} · {o.remote?'REMOTE':'IN PERSON'}</Eyebrow><Title style={{marginTop:13,fontSize:40,lineHeight:43}}>{o.title}</Title><View style={[s.row,{gap:6,marginTop:15}]}><Icon name="checkmark-circle" color={C.forest} size={16}/><Txt style={{color:C.muted,fontSize:13}}>{o.organization}</Txt></View>
 <View style={{marginTop:23,gap:10}}><View style={[s.row,{gap:10}]}><Icon name="calendar-outline" size={18}/><Txt>{fullDay(o.startsAt)}</Txt></View><View style={[s.row,{gap:10}]}><Icon name="time-outline" size={18}/><Txt>{time(o.startsAt)} – {time(o.endsAt)}</Txt></View><View style={[s.row,{gap:10}]}><Icon name={o.remote?'laptop-outline':'location-outline'} size={18}/><Txt style={{flex:1}}>{o.location}</Txt></View></View>
 <View style={{marginTop:25,gap:12}}>{application?<><View style={[s.row,{gap:10}]}><Badge status={application.status}/><Txt style={{fontSize:12,color:C.muted}}>Your application</Txt></View>{application.status==='accepted'?<Button title="Log your service" icon="add" onPress={()=>nav.sheet({kind:'log',id:application.id})}/>:application.status==='pending'?<Button title="Withdraw application" variant="outline" busy={busy} onPress={async()=>{setBusy(true);try{await app.withdraw(application.id);nav.notify('Application withdrawn.');}catch(e){nav.notify(errorText(e));}finally{setBusy(false);}}}/>:<Txt style={s.body}>{application.status==='withdrawn'?'Your application was withdrawn. Explore another opportunity.':'Your application was declined. Explore other opportunities that fit your interests.'}</Txt>}</>:<Button title={blocked||'I want to help'} disabled={!!blocked} icon="arrow-forward" onPress={()=>nav.sheet({kind:'apply',id:o.id})}/>}<Txt style={{fontSize:11,textAlign:'center',color:C.muted}}>For volunteers ages {o.minimumAge}+ · {remainingPlaces(o.capacity,o.spotsLeft)}</Txt></View>
 <Rule/><View style={[s.card,{gap:12,backgroundColor:C.green}]}><Eyebrow>Your personalized match</Eyebrow><Txt style={s.sectionTitle}>{match.score}% fit for you</Txt>{[...match.reasons,...match.unknown,...match.blockers].map(t=><Txt key={t} style={{lineHeight:22}}>{t}</Txt>)}<Button title="Adjust matching preferences" variant="outline" onPress={()=>nav.sheet({kind:'preferences'})}/></View>{o.outcomeMetric&&<View style={[s.card,{marginTop:16,gap:10}]}><Eyebrow>The change we’re working toward</Eyebrow><Txt style={{fontSize:21,fontWeight:'800'}}>{o.outcomeTarget} {o.outcomeMetric}</Txt><Txt style={s.body}>A project target, not a verified result. Your actual contribution is reviewed after service.</Txt></View>}
 <Rule/><Txt accessibilityRole="header" style={s.sectionTitle}>A little about the good</Txt><Txt style={[s.body,{marginTop:14}]}>{o.description}</Txt><Rule/>
 <Txt accessibilityRole="header" style={s.sectionTitle}>What to know</Txt><View style={{gap:14,marginTop:17}}>{[...o.requirements, o.proofRequired?'A photo or document is required with your service log.':'Add a short work note when you log your hours.'].map((r,i)=><View key={i} style={[s.row,{gap:12,alignItems:'flex-start'}]}><Icon name="checkmark-circle-outline" color={C.forest} size={19}/><Txt style={[s.body,{flex:1,fontSize:14,lineHeight:21}]}>{r}</Txt></View>)}</View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:20}}>{o.skills.map(skill=><Chip key={skill} label={skill}/>)}</View>
 {!o.remote&&<><Rule/><Txt accessibilityRole="header" style={s.sectionTitle}>Meet us here</Txt><View style={{backgroundColor:C.soft,borderRadius:22,padding:22,marginTop:16,gap:15}}><View style={[s.row,{gap:13}]}><Icon name="location-outline" size={27}/><View style={{flex:1}}><Txt style={{fontWeight:'700'}}>{o.location}</Txt><Txt style={[s.body,{fontSize:13,marginTop:4}]}>{o.address}</Txt></View></View><Button title="Open in Maps" icon="arrow-up-outline" variant="outline" onPress={()=>{void Linking.openURL(`https://maps.apple.com/?q=${encodeURIComponent(o.address||o.location)}`).catch(e=>nav.notify(errorText(e)));}}/></View></>}
 <Rule/><View style={{gap:12}}><Eyebrow>A note on service hours</Eyebrow><Txt style={s.body}>Hours count toward your verified record after the organization reviews and approves your work.</Txt><Button title="Get help with this opportunity" variant="soft" onPress={()=>nav.sheet({kind:'support',id:o.id})}/></View></View>;
}
