import React from 'react';
import { Pressable, ScrollView, View } from 'react-native';
import { useApp } from '../data/AppProvider';
import { useNav } from '../ui/navigation';
import { C, Eyebrow, Icon, Spark, Title, Txt, s } from '../ui/theme';
import { hours } from '../ui/helpers';
import { OpportunityCard } from '../ui/OpportunityCard';

export function Home() {
 const app = useApp(), nav = useNav(); const minutes = app.entries.filter(e => e.status === 'approved').reduce((a,e) => a+e.minutes,0); const goal = app.profile?.goalHours || 40;
 const next = app.applications.filter(a => a.status === 'accepted').map(a => app.opportunities.find(o => o.id === a.opportunityId)).filter(o => o && new Date(o.startsAt) > new Date()).sort((a,b) => a!.startsAt.localeCompare(b!.startsAt))[0];
 return <View style={{ paddingHorizontal: 24, paddingTop: 22, paddingBottom: 30 }}>
 <View style={s.between}><View style={[s.row,{gap: 7}]}><Spark size={24}/><Txt style={{ fontSize: 18, fontWeight: '900', letterSpacing: -.7 }}>voluforge</Txt></View><Pressable accessibilityRole="button" accessibilityLabel="Open your profile" onPress={() => nav.navigate('profile')} style={{ width: 39, height: 39, borderRadius: 100, backgroundColor: C.peach, alignItems: 'center', justifyContent: 'center' }}><Txt style={{ fontWeight: '800', fontSize: 12 }}>{app.profile?.name.split(' ').map(n=>n[0]).join('').slice(0,2) || 'VF'}</Txt></Pressable></View>
 <View style={{ marginTop: 34, marginBottom: 26 }}><Eyebrow>Hey {app.profile?.name.split(' ')[0] || 'there'}, let’s make a difference</Eyebrow><View style={[s.between, { alignItems: 'flex-end', marginTop: 13 }]}><Title style={{ fontSize: 45, lineHeight: 46, letterSpacing: -2 }}>A little time.{'\n'}A lot of good.</Title><View style={{ transform: [{rotate: '13deg'}], marginBottom: 7 }}><Spark size={47}/></View></View><Txt style={[s.body,{marginTop: 13, maxWidth: 300}]}>Find your people. Show up for your community.</Txt></View>
 <Pressable accessibilityRole="button" accessibilityLabel="View your impact" onPress={() => nav.navigate('impact')} style={{ backgroundColor: C.green, padding: 22, borderRadius: 24 }}><View style={s.between}><Eyebrow style={{ color: C.forest }}>{app.mode === 'demo' ? 'Your demo impact' : 'Your verified impact'}</Eyebrow><Icon name="sparkles-outline" color={C.forest} size={20}/></View><View style={[s.between, {marginTop: 12}]}><View style={[s.row,{alignItems: 'baseline',gap: 7}]}><Txt style={{ fontSize: 53, fontWeight: '900', letterSpacing: -2.5 }}>{hours(minutes)}</Txt><Txt style={{fontSize: 14}}>hours of good</Txt></View><View style={{width: 40,height:40,borderRadius:100,backgroundColor:C.ink,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-up-outline" color={C.white} size={19}/></View></View><View accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: goal, now: minutes/60 }} style={{ height: 5, borderRadius: 10, backgroundColor: '#C2D4B2', marginTop: 18, overflow: 'hidden' }}><View style={{ height: '100%', width: `${Math.min(minutes/60/goal*100,100)}%`, backgroundColor: C.forest }}/></View><View style={[s.between,{marginTop:10}]}><Txt style={{fontSize:11,color:C.forest}}>{Math.round(minutes/60/goal*100)}% of your personal goal</Txt><Txt style={{fontSize:11,fontWeight:'700',color:C.forest}}>{goal} hrs</Txt></View></Pressable>
 {next && <Pressable accessibilityRole="button" onPress={() => nav.detail(next.id)} style={[s.row,{gap:14,paddingVertical:20,borderBottomWidth:1,borderColor:C.line}]}><View style={{backgroundColor:C.soft,padding:13,borderRadius:15}}><Icon name="calendar-outline"/></View><View style={{flex:1,gap:5}}><Eyebrow>You’re up next</Eyebrow><Txt style={{fontWeight:'700',fontSize:14}}>{next.title}</Txt></View><Icon name="arrow-forward" size={18}/></Pressable>}
 <View style={[s.between,{marginTop:30,marginBottom:18}]}><Txt accessibilityRole="header" style={s.sectionTitle}>Good things to do</Txt><Pressable accessibilityRole="button" accessibilityLabel="See all opportunities" onPress={()=>nav.navigate('explore')} style={{padding:8,paddingRight:0}}><Txt style={{fontSize:12,fontWeight:'700'}}>See all ↗</Txt></Pressable></View>
 {app.opportunities.filter(o=>o.status==='open').slice(0,1).map(o=><OpportunityCard key={o.id} opportunity={o}/>)}
 {app.opportunities.filter(o=>o.status==='open').slice(1,3).map(o=><OpportunityCard compact key={o.id} opportunity={o}/>)}
 {app.opportunities.filter(o=>o.status==='open').length === 0 && <Txt style={s.body}>New opportunities will appear here when community partners publish them.</Txt>}
 <View style={[s.row,{gap:10,marginTop:25,justifyContent:'center'}]}><Spark size={16} color={C.forest}/><Txt style={{fontSize:11,color:C.muted}}>Small actions. Real-world change.</Txt></View>
 </View>;
}
