import {verifiedOutcomes} from '../data/impact';
import React from 'react';
import { View } from 'react-native';
import Svg, {Circle} from 'react-native-svg';
import {useApp} from '../data/AppProvider';
import {useNav} from '../ui/navigation';
import {C,Badge,Button,Empty,Eyebrow,Rule,Spark,Title,Txt,s} from '../ui/theme';
import {day,hours} from '../ui/helpers';

export function Impact(){const app=useApp(),nav=useNav();const outcomes=verifiedOutcomes(app.entries,app.outcomes);const totals=outcomes.reduce((acc,r)=>({...acc,[r.metric]:(acc[r.metric]??0)+r.quantity}),{} as Record<string,number>);const approved=app.entries.filter(e=>e.status==='approved');const minutes=approved.reduce((a,e)=>a+e.minutes,0),pending=app.entries.filter(e=>e.status==='pending').reduce((a,e)=>a+e.minutes,0),goal=app.profile?.goalHours||40;const circumference=2*Math.PI*85;const orgs=new Set(approved.map(e=>app.opportunities.find(o=>o.id===e.opportunityId)?.organizationId).filter(Boolean)).size;
 return <View style={{padding:24,paddingTop:29,paddingBottom:35}}><Eyebrow>Every hour has a story</Eyebrow><View style={[s.between,{marginTop:12}]}><Title>Look at the good{'\n'}you’ve done.</Title><Spark size={34}/></View>
 <View style={{alignItems:'center',marginTop:28,backgroundColor:C.green,borderRadius:26,padding:25}}><Eyebrow style={{color:C.forest}}>{app.mode==='demo'?'Sample impact · demo only':'Your approved service'}</Eyebrow><View style={{width:210,height:210,marginVertical:18,alignItems:'center',justifyContent:'center'}}><Svg width={210} height={210} style={{position:'absolute'}}><Circle cx={105} cy={105} r={85} fill="none" stroke="#C4D6B3" strokeWidth={9}/><Circle cx={105} cy={105} r={85} fill="none" stroke={C.forest} strokeWidth={9} strokeDasharray={`${circumference} ${circumference}`} strokeDashoffset={circumference*(1-Math.min(minutes/60/goal,1))} strokeLinecap="round" transform="rotate(-90 105 105)"/></Svg><Txt style={{fontSize:65,fontWeight:'900',letterSpacing:-3}}>{hours(minutes)}</Txt><Txt style={{fontSize:13,marginTop:0}}>hours of impact</Txt><Txt style={{fontSize:11,color:C.forest,marginTop:8}}>of your {goal}-hour goal</Txt></View><Txt style={{fontWeight:'600',fontSize:13}}>{minutes/60>=goal?'You reached your goal. Keep the good going.':`${hours(Math.max(0,goal*60-minutes))} more hours to your personal goal.`}</Txt></View>
 <View style={[s.row,{paddingVertical:24}]}>{[{n:approved.length,l:'Approved entries'},{n:orgs,l:'Organizations'},{n:hours(pending),l:'Hours in review'}].map((v,i)=><View key={v.l} style={{flex:1,alignItems:'center',borderRightWidth:i<2?1:0,borderColor:C.line,gap:7}}><Txt style={{fontSize:27,fontWeight:'800',letterSpacing:-1}}>{v.n}</Txt><Txt style={{fontSize:10,color:C.muted}}>{v.l}</Txt></View>)}</View>
 <Rule/><Eyebrow>Good beyond the hours</Eyebrow><Txt style={[s.sectionTitle,{marginVertical:14}]}>Concrete results.</Txt>{Object.entries(totals).map(([metric,quantity])=><View key={metric} style={[s.card,{marginBottom:12,backgroundColor:C.peach,gap:6}]}><Txt style={{fontSize:36,fontWeight:'900'}}>{quantity}</Txt><Txt style={{fontWeight:'700'}}>{metric}</Txt><Txt style={{fontSize:11,color:C.muted}}>{app.mode==='demo'?'Fictional sample approval':'Independently approved by the partner'}</Txt></View>)}{!outcomes.length&&<Txt style={s.body}>Approved outcomes will appear here after a partner verifies your contribution.</Txt>}<View style={{gap:12,marginVertical:18}}><Button title="Record a concrete outcome" variant="outline" onPress={()=>nav.sheet({kind:'outcome'})}/><Button title="See your Impact Graph" variant="soft" icon="git-network-outline" onPress={()=>nav.sheet({kind:'connections'})}/><Button title="Explore community needs & research" variant="soft" onPress={()=>nav.sheet({kind:'insights'})}/></View>{app.outcomes.filter(r=>r.status!=='approved').map(r=><View key={r.id} style={[s.card,{gap:8,marginBottom:12}]}><Badge status={r.status}/><Txt>{r.quantity} {r.metric}</Txt><Txt style={s.body}>{r.review_note||'Waiting for independent partner review.'}</Txt></View>)}
 <Button title={app.mode==='demo'?'Export sample record':'Export verified record'} icon="download-outline" onPress={()=>nav.sheet({kind:'export'})}/><Txt style={{textAlign:'center',fontSize:11,color:C.muted,marginTop:12,lineHeight:17}}>{app.mode==='demo'?'Sample records are watermarked and are not proof of service.':'Only organization-approved hours appear on your record.'}</Txt><Rule/><Txt style={s.sectionTitle}>Your service story</Txt>
 {approved.map(e=><View key={e.id} style={{paddingVertical:19,borderBottomWidth:1,borderColor:C.line,gap:9}}><View style={s.between}><Txt style={{fontSize:12,color:C.muted}}>{day(e.date)}</Txt><Txt style={{fontSize:16,fontWeight:'800'}}>{hours(e.minutes)} hrs</Txt></View><Txt style={{fontWeight:'700',fontSize:15}}>{app.opportunities.find(o=>o.id===e.opportunityId)?.title??'Completed service'}</Txt><View style={[s.row,{gap:8}]}><Badge status="approved"/>{e.reviewerName&&<Txt style={{fontSize:10,color:C.muted,flex:1}}>Reviewed by {e.reviewerName}</Txt>}</View></View>)}{approved.length===0&&<Empty title="Your impact is on its way" text="Your approved hours will appear here after an organization reviews your service."/>}
 </View>;
}
