import {useDesktop} from '../ui/responsive';
import {BrandMark} from '../ui/BrandMark';
import React from 'react';
import { Platform, Pressable, View } from 'react-native';
import { useApp } from '../data/AppProvider';
import { useNav } from '../ui/navigation';
import { C, Button, Eyebrow, Spark, Sprout, Title, Txt, s } from '../ui/theme';
import { errorText } from '../ui/helpers';

export function Welcome(){const app=useApp(),nav=useNav(),desktop=useDesktop();if(desktop)return <DesktopWelcome/>;return <View style={{flex:1,padding:28,paddingTop:28,minHeight:740}}><View style={[s.row,{gap:8}]}><BrandMark size={30}/><Txt style={{fontWeight:'900',fontSize:21,letterSpacing:-.8}}>voluforge</Txt></View><View style={{flex:1,justifyContent:'center',paddingVertical:40}}><View style={{alignSelf:'flex-end',transform:[{rotate:'12deg'}],marginRight:8,marginBottom:-20}}><Sprout size={126}/></View><Title style={{fontSize:64,lineHeight:66,letterSpacing:-2.3}}>Do a little.{'\n'}Change{'\n'}a <Txt style={{fontStyle:'italic',fontWeight:'500',fontSize:64}}>lot.</Txt></Title><Txt style={[s.body,{fontSize:17,lineHeight:26,marginTop:25,maxWidth:290}]}>Find meaningful ways to give back. Turn your time into something that matters.</Txt>{Platform.OS!=='web'&&<Eyebrow style={{marginTop:27,color:C.forest}}>Your next good thing starts here</Eyebrow>}</View><View style={{gap:13}}><Button title="Get started" icon="arrow-forward" onPress={()=>nav.sheet({kind:'auth',id:'signup'})}/><Button title="Take a look around" variant="outline" onPress={()=>{void app.enterDemo().catch(e=>nav.notify(errorText(e)));}} busy={app.loading}/><Txt style={{textAlign:'center',fontSize:11,color:C.muted,lineHeight:18}}>Explore sample opportunities, no account needed.</Txt><View style={[s.row,{justifyContent:'center',gap:15,marginTop:4}]}><Pressable accessibilityRole="link" onPress={()=>nav.sheet({kind:'privacy'})}><Txt style={{fontSize:11,textDecorationLine:'underline',color:C.muted}}>Privacy</Txt></Pressable><Pressable accessibilityRole="link" onPress={()=>nav.sheet({kind:'terms'})}><Txt style={{fontSize:11,textDecorationLine:'underline',color:C.muted}}>Terms</Txt></Pressable></View></View></View>;}

function DesktopWelcome(){const app=useApp(),nav=useNav();return <View style={{padding:48,minHeight:720,flex:1}}><View style={[s.between,{marginBottom:50}]}><View style={[s.row,{gap:10}]}><BrandMark size={38}/><Txt style={{fontSize:27,fontWeight:'900',letterSpacing:-1}}>voluforge</Txt></View><Button title="Sign in" variant="outline" onPress={()=>nav.sheet({kind:'auth'})}/></View><View style={{flex:1,flexDirection:'row',alignItems:'center',gap:48}}><View style={{flex:1,gap:25}}><Title style={{fontSize:72,lineHeight:78,letterSpacing:-2.4}}>Do a little.{'\n'}Change a <Txt style={{fontSize:72,fontStyle:'italic',fontWeight:'500'}}>lot.</Txt></Title><Txt style={[s.body,{fontSize:19,lineHeight:30,maxWidth:450}]}>Find meaningful ways to give back. Turn your time into something that matters.</Txt><View style={[s.row,{gap:12,flexWrap:'wrap',marginTop:10}]}><Button title="Get started" icon="arrow-forward" onPress={()=>nav.sheet({kind:'auth',id:'signup'})}/><Button title="Take a look around" variant="outline" busy={app.loading} onPress={()=>{void app.enterDemo().catch(e=>nav.notify(errorText(e)));}}/></View><Txt style={{fontSize:12,color:C.muted}}>Explore sample opportunities, no account needed.</Txt></View><View style={{width:320,alignItems:'center',gap:24}}><Sprout size={300}/><View style={{backgroundColor:C.peach,borderRadius:16,padding:24,gap:10,width:300}}><Txt style={{fontSize:21,fontWeight:'800'}}>Your skills. Someone’s spark.</Txt><Txt style={[s.body,{color:C.ink}]}>Find your fit. Show up. See what changes.</Txt><Txt style={{fontSize:12,color:C.ink,marginTop:5}}>Small actions. Real-world change.</Txt></View></View></View><View style={[s.between,{borderTopWidth:1,borderColor:C.line,paddingTop:24,marginTop:40}]}><Txt style={{fontSize:12,color:C.muted}}>Made for a little more good.</Txt><View style={[s.row,{gap:24}]}>{['privacy','terms','support'].map(kind=><Pressable key={kind} accessibilityRole="link" onPress={()=>nav.sheet({kind:kind as 'privacy'|'terms'|'support'})}><Txt style={{fontSize:12,color:C.muted}}>{kind[0].toUpperCase()+kind.slice(1)}</Txt></Pressable>)}</View></View></View>;}
