import React from 'react';
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, TextInput, View, type StyleProp, type TextStyle, type ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import Svg, { Path, Circle, G, Rect } from 'react-native-svg';

export const C = { bg: '#F8F5ED', ink: '#191B16', muted: Platform.OS === 'web' ? '#62665B' : '#73756B', line: '#DEDCD2', orange: '#DB582C', peach: '#F3D7C3', green: '#DDEBCB', forest: '#3D5736', white: '#FFFDF8', soft: '#ECEBE1', red: '#AD3429', blue: '#DBE7EC' };
export type IconName = React.ComponentProps<typeof Ionicons>['name'];
export function Icon({ name, size = 22, color = C.ink }: { name: IconName; size?: number; color?: string }) { return <Ionicons name={name} size={size} color={color} />; }
export function Txt({ children, style, ...rest }: React.ComponentProps<typeof Text>) { const flat=StyleSheet.flatten(style), trackingFloor=-.04*(flat?.fontSize??15); const tracking=Platform.OS==='web'&&typeof flat?.letterSpacing==='number'&&flat.letterSpacing<trackingFloor?{letterSpacing:trackingFloor}:undefined; return <Text {...rest} style={[s.text, style,tracking]}>{children}</Text>; }
export function Title({ children, style }: { children: React.ReactNode; style?: StyleProp<TextStyle> }) { return <Txt accessibilityRole="header" style={[s.title, style]}>{children}</Txt>; }
export function Eyebrow({ children, style }: { children: React.ReactNode; style?: StyleProp<TextStyle> }) { return <Txt testID="vf-section-label" style={[s.eyebrow, style]}>{children}</Txt>; }
export function Spark({ size = 42, color = C.orange }: { size?: number; color?: string }) { return <Svg width={size} height={size} viewBox="0 0 100 100" {...(Platform.OS === 'web' ? {'aria-hidden': true} : {accessibilityElementsHidden: true})}><G>{Array.from({ length: 8 }, (_, i) => <Rect key={i} x="44" y="5" width="12" height="45" rx="6" fill={color} transform={`rotate(${i * 45} 50 50)`} />)}</G><Circle cx="50" cy="50" r="12" fill={C.ink} /></Svg>; }
export function Sprout({ size = 170 }: { size?: number }) { return <Svg width={size} height={size} viewBox="0 0 180 180"><Circle cx="90" cy="90" r="85" fill={C.green}/><Path d="M91 137C93 111 88 88 67 65" stroke={C.forest} strokeWidth="7" fill="none" strokeLinecap="round"/><Path d="M91 103C100 76 118 64 135 56" stroke={C.forest} strokeWidth="7" fill="none" strokeLinecap="round"/><Path d="M85 86C45 87 37 67 39 44C73 39 93 61 85 86Z" fill={C.forest}/><Path d="M96 101C102 65 126 58 149 65C151 93 130 111 96 101Z" fill={C.forest}/><Path d="M59 139Q90 122 121 139" stroke={C.forest} strokeWidth="6" fill="none" strokeLinecap="round"/></Svg>; }
export function Button({ title, onPress, icon, variant = 'primary', disabled, busy, style, testID }: { title: string; onPress: () => void; icon?: IconName; variant?: 'primary'|'outline'|'soft'|'danger'; disabled?: boolean; busy?: boolean; style?: StyleProp<ViewStyle>; testID?: string }) {
 const dark = variant === 'primary' || variant === 'danger';
 return <Pressable testID={testID || 'vf-button'} accessibilityLabel={title} accessibilityRole="button" accessibilityState={{ disabled: !!disabled || !!busy, busy: !!busy }} disabled={disabled || busy} onPress={onPress} style={({ pressed }) => [s.button, variant === 'outline' && s.outline, variant === 'soft' && { backgroundColor: C.soft }, variant === 'danger' && { backgroundColor: C.red }, (disabled || busy) && { opacity: .45 }, pressed && { opacity: .75, transform: [{ scale: .99 }] }, style]}>{busy ? <ActivityIndicator color={dark ? C.white : C.ink} /> : <><Txt style={[s.buttonText, { color: dark ? C.white : C.ink }]}>{title}</Txt>{icon && <Icon name={icon} color={dark ? C.white : C.ink} size={20} />}</>}</Pressable>;
}
export function IconButton({ name, label, onPress, active, style }: { name: IconName; label: string; onPress: () => void; active?: boolean; style?: StyleProp<ViewStyle> }) { return <Pressable testID="vf-icon-button" accessibilityRole="button" hitSlop={6} accessibilityLabel={label} accessibilityState={{ selected: !!active }} onPress={onPress} style={({ pressed }) => [s.iconButton, active && { backgroundColor: C.ink }, pressed && { opacity: .6 }, style]}><Icon name={name} color={active ? C.white : C.ink}/></Pressable>; }
export function Chip({ label, selected, onPress, icon }: { label: string; selected?: boolean; onPress?: () => void; icon?: IconName }) { return <Pressable testID="vf-chip" accessibilityRole={onPress ? 'button' : undefined} accessibilityState={onPress ? {selected: !!selected} : undefined} onPress={onPress} style={[s.chip, selected && { backgroundColor: C.ink, borderColor: C.ink }]}>{icon && <Icon name={icon} size={16} color={selected ? C.white : C.ink}/>}<Txt style={{ fontSize: 13, fontWeight: '600', color: selected ? C.white : C.ink }}>{label}</Txt></Pressable>; }
export function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={{ gap: 8 }}><Txt style={{ fontSize: 13, fontWeight: '700' }}>{label}</Txt><TextInput accessibilityLabel={label} placeholderTextColor={C.muted} {...props} style={[s.input, props.multiline && { minHeight: 104, textAlignVertical: 'top', paddingTop: 15 }, props.style]}/></View>; }
export function Rule() { return <View style={{ height: 1, backgroundColor: C.line, marginVertical: 24 }}/>; }
export function Empty({ icon = 'leaf-outline', title, text, action }: { icon?: IconName; title: string; text: string; action?: React.ReactNode }) { return <View style={{ paddingVertical: 36, gap: 14, alignItems: 'center' }}><View style={{ backgroundColor: C.soft, padding: 20, borderRadius: 100 }}><Icon name={icon} size={28}/></View><Txt style={{ fontSize: 20, fontWeight: '700', textAlign: 'center' }}>{title}</Txt><Txt style={{ color: C.muted, lineHeight: 23, textAlign: 'center', maxWidth: 300 }}>{text}</Txt>{action}</View>; }
export function Badge({ status }: { status: string }) { const good = ['accepted', 'approved', 'open'].includes(status); return <View style={{ alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 30, backgroundColor: good ? C.green : status === 'rejected' || status === 'declined' ? C.peach : C.soft }}><Txt style={{ fontSize: 11, fontWeight: '700', color: good ? C.forest : C.ink }}>{status.replaceAll('_', ' ').toUpperCase()}</Txt></View>; }
export const s = StyleSheet.create({
 text: { fontSize: 15, color: C.ink, fontFamily: Platform.OS === 'web' ? 'DM Sans' : undefined }, title: { fontSize: 38, lineHeight: 41, fontWeight: '900', letterSpacing: Platform.OS === 'web' ? -1.1 : -1.6 }, eyebrow: { fontSize: 10, fontWeight: '700', letterSpacing: 1.8, color: C.muted, textTransform: 'uppercase' },
 row: { flexDirection: 'row', alignItems: 'center' }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
 button: { backgroundColor: C.ink, minHeight: Platform.OS === 'web' ? 48 : 54, paddingHorizontal: 24, paddingVertical: 15, borderRadius: Platform.OS === 'web' ? 12 : 100, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10 }, buttonText: { fontSize: 15, fontWeight: '700' }, outline: { backgroundColor: 'transparent', borderWidth: 1.4, borderColor: C.ink },
 iconButton: { width: 46, height: 46, borderRadius: 100, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center' }, chip: { borderRadius: 100, borderWidth: 1, borderColor: C.line, paddingHorizontal: 15, minHeight: 44, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 7 }, input: { backgroundColor: C.white, borderColor: C.line, borderWidth: 1, borderRadius: Platform.OS === 'web' ? 10 : 15, padding: 15, fontSize: 16, color: C.ink, minHeight: 52 },
 sectionTitle: { fontSize: 24, fontWeight: '800', letterSpacing: -.7 }, card: { backgroundColor: C.white, borderRadius: Platform.OS === 'web' ? 16 : 22, padding: 20 }, body: { color: C.muted, lineHeight: 24 },
});
