import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {initializeLocalDatabase} from './local-db.mjs';
const db=new PGlite();const student='11111111-1111-4111-8111-111111111111',staff='22222222-2222-4222-8222-222222222222',other='33333333-3333-4333-8333-333333333333',org='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',opp='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',app='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
async function as(id,fn){await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);try{return await fn()}finally{await db.exec('reset role')}}
try{await initializeLocalDatabase(db);await db.exec(`insert into auth.users(id) values('${student}'),('${staff}'),('${other}');insert into public.vf_organizations(id,name,verified) values('${org}','Native partner',true);insert into public.vf_org_staff(org_id,user_id) values('${org}','${staff}');insert into public.vf_opportunities(id,org_id,title,description,category,starts_at,ends_at,capacity,status,outcome_metric) values('${opp}','${org}','Pack meal kits','Pack balanced meal kits for the community.','Food security',now()-interval '1 day',now()+interval '1 day',10,'published','kits packed');insert into public.vf_applications(id,student_id,opportunity_id,message,availability,status) values('${app}','${student}','${opp}','I can pack meal kits.','Available','accepted');`);
const submit=(quantity,id=null)=>as(student,()=>db.query("select * from public.vf_submit_mobile_impact($1,current_date,60,'Packed balanced meal kits.','kits packed',$2,'Coordinator tally recorded the kits.',null,$3)",[app,quantity,id]));
await assert.rejects(()=>submit(-2),/check constraint/);assert.equal((await db.query('select count(*) from public.vf_service_entries')).rows[0].count,0);
const {rows:[entry]}=await submit(4);assert.equal(Number((await db.query('select quantity from public.vf_outcomes')).rows[0].quantity),4);
await as(other,()=>assert.rejects(()=>db.query("select public.vf_record_outcome($1,'kits packed',5,'Coordinator confirmed five kits.')",[entry.id]),/unavailable/));
await as(student,()=>assert.rejects(()=>db.query("select public.vf_record_outcome($1,'kits packed',5,'Coordinator confirmed five kits.')",[entry.id]),/already submitted/));
await as(staff,()=>db.query("select public.vf_review_service($1,'changes_requested','Please correct the kit tally.')",[entry.id]));
await submit(5,entry.id);assert.equal(Number((await db.query('select quantity from public.vf_outcomes')).rows[0].quantity),5);assert.equal((await db.query('select count(*) from public.vf_service_entries')).rows[0].count,1);
const outcome=(await db.query('select * from public.vf_outcomes')).rows[0];await as(staff,()=>db.query("select public.vf_review_service($1,'approved','Tally reviewed.')",[entry.id]));await as(staff,()=>db.query("select public.vf_review_impact($1,'rejected','Tally is incomplete.')",[outcome.id]));
await as(student,()=>db.query("select public.vf_record_outcome($1,'kits packed',6,'Coordinator confirmed the updated tally.')",[entry.id]));assert.equal((await db.query('select status from public.vf_outcomes')).rows[0].status,'pending');await as(staff,()=>db.query("select public.vf_review_impact($1,'approved')",[outcome.id]));await as(student,()=>assert.rejects(()=>db.query("select public.vf_record_outcome($1,'kits packed',99,'Trying to change an approved outcome.')",[entry.id]),/already submitted/));
console.log('PASS: native atomic time/outcome submission, returned-service revision, owner isolation, duplicate prevention, rejected-outcome resubmission, approved immutability');
}finally{await db.close()}
